### ISSUE TITLE
Create an Object for Tasks

### ISSUE THREAD

**Issue by pouyamn** [MP-holding/taskmangoal#3]
The task should keep following data:
- ID
- Summery
- User
- Due date
- Priority (1 to 5)
- Progress (0-100)
- Is it Done or not

It should do following tasks:
- Create
- Print
- Save (in a separate File)
- Load from file
- Provide Dictionary of it attributes

**Comment by PilaPont** [comment]
progress = 100, means task is done. Therefore it's not needed to define "is don or not" as a separated variable.

**Comment by PilaPont** [comment]
it seems better to use the Str presentation instead of print function in a class.
