### ISSUE TITLE
Create Object for Users

### ISSUE THREAD

**Issue by pouyamn** [MP-holding/taskmangoal#4]
Create a User Object with the following members:
# Attributes:
- ID:String
- Username:String
- FirstName:string
-  LastName:string
-  Passwordhash:hash 
- Gender:string
# Methods: 
- GetFullName():string->Title+Firstname+LastName
- Authenticate(password):Boolean
# Other:
It should have a class variable that defines the titles for each gender

**Comment by PilaPont** [comment]
Is it necessary to define a users manager object or it is enough to keep a list of users?

**Comment by PilaPont** [comment]
Could you please create a new card for task manager?

**Comment by pouyamn** [comment]
> Could you please create a new card for task manager?

Yep, I did but why your comment is here under *Create Object for Users*?

**Comment by pouyamn** [comment]
> Is it necessary to define a users manager object or it is enough to keep a list of users?

It's up to you, but if it were me, I would use it. For actions like write to disk or maybe we could use it for other tasks such as preventing to make duplicate users
